#############################################################
# Database Backup Configuration
# Format:
# DATABASE_NAME|DATABASE_USERNAME|DATABASE_PASSWORD
#############################################################

idealgro_web|idealgro_u_web|KSG(ZYw4&!%i



